network:
  name: "CustomBlockchain"
  apiPort: 8080
  p2pPort: 8081
  peers: []
consensus:
  type: "PoW" # Options: PoW, PoS, PBFT
  difficulty: 3
block:
  maxSize: 1 # in MB
smartContracts:
  enabled: true
wallet:
  enabled: true
  balance: 1000
bootstrapNodes:
  - "192.168.1.2:8081"
  - "192.168.1.3:8081"
  - "peer1.example.com:8081"
